### ISSUE TITLE
Undune2 working but graphics corrupted

### ISSUE THREAD

**Issue by nckstwrt** [jtothebell/fake-08#143] opened 2022-07-05 12:28 UTC
Tried latest build on MiyooMini and Windows SDL2 and got the same result:
![](https://i.imgur.com/JFdLGCI.png)

It looks like this on Pico8:
![](https://i.imgur.com/QTRvlUk.png)

The "select" icon appears instead as a hexadecimal string when selecting vehicles and the title bar is corrupted.

**Comment by jtothebell** [comment] 2022-07-08 03:13
Thanks for the report. I noticed these issues as well when I got this game working, but haven't yet done more thorough investigation into the root causes.

**Comment by jtothebell** [comment] 2022-07-11 02:37
The two issues described should be fixed now. Both had to do with P8SCII control codes not matching pico 8 behavior. I assume those control codes were used to save tokens. I'm going to leave this open though, because although Undune is arguably playable, the map is still not correct, the build menu text is not placed correctly, and there may well be other issues.

**Comment by jtothebell** [comment] 2022-10-13 03:24
Most of the graphical issues on Undune 2 should be fixed now, and it seems to be playable in my quick tests. The up and down arrows in the build menu are still not rendering though. I think I have the bug narrowed down to an lua issue the combination of a shorthand if and shorthand print.

**Closed** 2024-01-15 17:32 UTC
Labels: bug
