### ISSUE TITLE
Powkiddy V90: visual glitch in "goblike"

### ISSUE THREAD

**Issue by Torkapp** [jtothebell/fake-08#137] opened 2022-06-28 03:09 UTC
When loading "goblike" by datagoblin (https://datagoblin.itch.io/goblike) the game boots up perfectly but sprites show up very incorrectly on screen.

**Comment by jtothebell** [comment] 2022-06-29 02:11
It looks like whatever the root cause of this issue was, it has been fixed in some recent updates that haven't been released yet. When I run the latest build I don t have the problem. Attaching it here so you can try it on your device.

[Bittboy.zip](https://github.com/jtothebell/fake-08/files/9006686/Bittboy.zip)

**Closed** 2022-07-11 02:37 UTC
