### ISSUE TITLE
Request: Virtual Keyboard/Control Rebinding

### ISSUE THREAD

**Issue by RandomMan25XX** [jtothebell/fake-08#126] opened 2022-05-14 04:23 UTC
I figure this would be a worthwhile addition as there are some games that do make use of a keyboard input, as for rebinding the existing inputs I've only mainly encountered an issue with PooM, mainly that the start button is used for switching weapons, so maybe either being able to rebind the controls to work around that for games that use the start button for various things or simply changing the button used to open the menu to exit a game

**Comment by DPS2004** [comment] 2022-05-15 14:27
hm, the poom issue is odd, because there should be support for suppressing the pause menu via a poke. Not sure why that's not working in this case. What platform are you on?

**Comment by RandomMan25XX** [comment] 2022-05-15 23:06
I'm using the 3ds version

**Comment by jtothebell** [comment] 2022-05-17 03:03
There is a bug with poom where the pause menu doesn't behave correctly. When you hit start (on the 3ds) it should bring up the weapon menu, and when you hit it again, it should bring up the normal pause menu, but that doesn't work. I've started looking in to it, but haven't had much time lately and haven't gotten to the bottom of it.

Key rebinding is something that we'd like to do, but not sure when.

**Comment by jtothebell** [comment] 2024-01-15 17:32
This is more or less a duplicate of #53  closing.

**Closed by jtothebell** 2024-01-15 17:32 UTC
Labels: enhancement
